### ISSUE TITLE
Asking for password to see the live demo

### ISSUE THREAD

**Issue by wheredidfranciscogo** [daviddarnes/gatsby-starter-ghost-blog#1]
Hello David

I encountered this issue when I'm trying to access to the demo:
<img width="634" alt="Screen Shot 2022-06-23 at 3 23 12 pm" src="https://user-images.githubusercontent.com/61140677/175221362-0eaefb20-3aea-4ccb-a60e-c46e8519fbd5.png">

Regards,

@wheredidfranciscogo

**Comment by daviddarnes** [comment]
Yea that's intentional, you should really look at the official starter instead https://github.com/TryGhost/gatsby-starter-ghost
